behaviors:
  KartAgent:
    trainer_type: ppo
    hyperparameters:
      beta: 0.01
      batch_size: 512
      buffer_size: 2048
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      use_recurrent: true
      sequence_length: 4
      memory_size: 256
    max_steps: 10.0e6
    time_horizon: 128
    summary_freq: 2048