behaviors:
  KartAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 265
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.992
      num_epoch: 16
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000000
    time_horizon: 128
    summary_freq: 256
    threaded: true

