behaviors:
  KartAgent:
    trainer_type: ppo
    hyperparameters:
      beta: 0.01
      batch_size: 512
      buffer_size: 2048
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    max_steps: 4e6
    time_horizon: 128
    summary_freq: 1024
